name: "Visitor Management System"
version: "1.0.2"
slug: "visitor-management-system"
description: "A comprehensive visitor management system for tracking visitors with sign-in/out capabilities and admin backend"
url: "https://github.com/goatboynz/HA-VMS"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8080
panel_icon: "mdi:account-group"
panel_title: "Visitor Management"
panel_admin: false
ports:
  8080/tcp: null
options:
  admin_username: "admin"
  admin_password: "changeme"
  database_path: "/data/visitors.db"
  max_file_size: 10485760
schema:
  admin_username: "str"
  admin_password: "str"
  database_path: "str"
  max_file_size: "int(1048576,52428800)"
image: "ghcr.io/goatboynz/ha-vms:latest"