version: '3.8'

services:
  visitor-management:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=changeme
      - DATABASE_PATH=/data/visitors.db
      - MAX_FILE_SIZE=10485760
    volumes:
      - ./data:/data
    restart: unless-stopped